version: "2"

services:
  
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/:/home/node/app
    command: "npm start"
  
  node2:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/:/home/node/app
    command: "npm start"
  
  nodeApi:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./appApi/:/home/node/app
    command: "npm start"
    
  ngix:
    image: "nginx"
    volumes:
      - ./var/www/:/etc/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    expose:
      - 80
